# Generated by Django 2.0.2 on 2018-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabride',
            name='jourtype',
            field=models.CharField(choices=[('Single Journey', 'single_journey'), ('Round Trip', 'Round trip')], max_length=20, null=True),
        ),
    ]
