# Generated by Django 2.0.2 on 2018-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180320_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_mob',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mob_no',
            field=models.IntegerField(default=0),
        ),
    ]
