# Generated by Django 2.0.2 on 2018-03-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180322_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabride',
            name='distance',
        ),
    ]
