# Generated by Django 2.0.2 on 2018-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cabride_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabride',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
