# Generated by Django 2.0.2 on 2018-03-22 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cabride_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabride',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
